name: Update Packages

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'

jobs:
  build-and-test:
    name: Update Packages
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          ref: master
      - name: Setup GitHub config
        run: |
          git config --local user.name "BotPatty"
          git config --local user.email "ci@zint.ch"
      - name: Install SSH Key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.GH_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.GH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: Update Packages
        run: |
          chmod +x packager.sh
          ./packager.sh
